"""Add message to join request

Revision ID: 4424dfbc302f
Revises: 920cc78eb2b8
Create Date: 2026-08-20 22:28:39.312195
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4424dfbc302f'
down_revision: Union[str, Sequence[str], None] = '920cc78eb2b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip_join_requests', sa.Column('message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trip_join_requests', 'message')
    # ### end Alembic commands ###
