"""add authorization provider and reservation workflow

Revision ID: 94ab2483e146
Revises: e3a51a694526
Create Date: 2026-08-17 00:12:30.637110
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '94ab2483e146'
down_revision: Union[str, Sequence[str], None] = 'e3a51a694526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource_type', sa.String(length=80), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_table('provider_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("verification_status IN ('pending', 'approved', 'rejected', 'suspended')", name='ck_provider_profiles_status'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_provider_profiles_status', 'provider_profiles', ['verification_status'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('granted_by', sa.Uuid(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_roles_user_role')
    )
    op.create_index('ix_user_roles_role_id', 'user_roles', ['role_id'], unique=False)
    op.create_index('ix_user_roles_user_id', 'user_roles', ['user_id'], unique=False)
    op.create_table('provider_documents',
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('document_type', sa.String(length=60), nullable=False),
    sa.Column('file_url', sa.String(length=1000), nullable=False),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("verification_status IN ('pending', 'approved', 'rejected')", name='ck_provider_documents_status'),
    sa.ForeignKeyConstraint(['provider_id'], ['provider_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_provider_documents_provider_id', 'provider_documents', ['provider_id'], unique=False)
    op.create_table('tours',
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('destination_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('inclusions', sa.Text(), nullable=True),
    sa.Column('exclusions', sa.Text(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('display_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('external_checkout_url', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'pending_review', 'published', 'paused', 'archived', 'rejected')", name='ck_tours_status'),
    sa.CheckConstraint('capacity > 0', name='ck_tours_capacity_positive'),
    sa.CheckConstraint('display_price >= 0', name='ck_tours_price_nonnegative'),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['provider_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tours_destination_id', 'tours', ['destination_id'], unique=False)
    op.create_index('ix_tours_provider_id', 'tours', ['provider_id'], unique=False)
    op.create_index('ix_tours_status', 'tours', ['status'], unique=False)
    op.create_table('tour_departures',
    sa.Column('tour_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('remaining_capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('scheduled', 'closed', 'cancelled', 'completed')", name='ck_tour_departures_status'),
    sa.CheckConstraint('capacity > 0', name='ck_tour_departures_capacity_positive'),
    sa.CheckConstraint('end_date >= start_date', name='ck_tour_departures_dates'),
    sa.CheckConstraint('remaining_capacity >= 0', name='ck_tour_departures_remaining_nonnegative'),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tour_departures_tour_dates', 'tour_departures', ['tour_id', 'start_date', 'end_date'], unique=False)
    op.create_table('tour_reservation_requests',
    sa.Column('tour_id', sa.Uuid(), nullable=False),
    sa.Column('departure_id', sa.Uuid(), nullable=False),
    sa.Column('traveler_id', sa.Uuid(), nullable=False),
    sa.Column('traveler_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('external_reference', sa.String(length=240), nullable=True),
    sa.Column('provider_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('requested', 'approved', 'rejected', 'cancelled', 'completed')", name='ck_reservations_status'),
    sa.CheckConstraint('traveler_count > 0', name='ck_reservations_traveler_count_positive'),
    sa.ForeignKeyConstraint(['departure_id'], ['tour_departures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['traveler_id'], ['profiles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reservations_departure_id', 'tour_reservation_requests', ['departure_id'], unique=False)
    op.create_index('ix_reservations_status', 'tour_reservation_requests', ['status'], unique=False)
    op.create_index('ix_reservations_traveler_id', 'tour_reservation_requests', ['traveler_id'], unique=False)
    op.add_column('profiles', sa.Column('account_status', sa.String(length=20), server_default='active', nullable=False))
    op.alter_column('profiles', 'account_status', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'account_status')
    op.drop_index('ix_reservations_traveler_id', table_name='tour_reservation_requests')
    op.drop_index('ix_reservations_status', table_name='tour_reservation_requests')
    op.drop_index('ix_reservations_departure_id', table_name='tour_reservation_requests')
    op.drop_table('tour_reservation_requests')
    op.drop_index('ix_tour_departures_tour_dates', table_name='tour_departures')
    op.drop_table('tour_departures')
    op.drop_index('ix_tours_status', table_name='tours')
    op.drop_index('ix_tours_provider_id', table_name='tours')
    op.drop_index('ix_tours_destination_id', table_name='tours')
    op.drop_table('tours')
    op.drop_index('ix_provider_documents_provider_id', table_name='provider_documents')
    op.drop_table('provider_documents')
    op.drop_index('ix_user_roles_user_id', table_name='user_roles')
    op.drop_index('ix_user_roles_role_id', table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index('ix_provider_profiles_status', table_name='provider_profiles')
    op.drop_table('provider_profiles')
    op.drop_index('ix_audit_logs_resource', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('roles')
    # ### end Alembic commands ###
