"""Add visibility to trips

Revision ID: b6c393521226
Revises: c2d29119e0f5
Create Date: 2026-08-20 22:22:08.817653
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b6c393521226'
down_revision: Union[str, Sequence[str], None] = 'c2d29119e0f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('visibility', sa.String(length=20), server_default='private', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'visibility')
    # ### end Alembic commands ###
