"""Add TripInvitation and TripJoinRequest

Revision ID: c2d29119e0f5
Revises: 94ab2483e146
Create Date: 2026-08-17 15:25:58.066595
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c2d29119e0f5'
down_revision: Union[str, Sequence[str], None] = '94ab2483e146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_invitations',
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('inviter_id', sa.Uuid(), nullable=False),
    sa.Column('invitee_email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'accepted', 'declined', 'cancelled')", name='ck_trip_invitations_status'),
    sa.ForeignKeyConstraint(['inviter_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trip_invitations_invitee_email', 'trip_invitations', ['invitee_email'], unique=False)
    op.create_index('ix_trip_invitations_trip_id', 'trip_invitations', ['trip_id'], unique=False)
    op.create_table('trip_join_requests',
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected', 'cancelled')", name='ck_trip_join_requests_status'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trip_join_requests_trip_id', 'trip_join_requests', ['trip_id'], unique=False)
    op.create_index('ix_trip_join_requests_user_id', 'trip_join_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trip_join_requests_user_id', table_name='trip_join_requests')
    op.drop_index('ix_trip_join_requests_trip_id', table_name='trip_join_requests')
    op.drop_table('trip_join_requests')
    op.drop_index('ix_trip_invitations_trip_id', table_name='trip_invitations')
    op.drop_index('ix_trip_invitations_invitee_email', table_name='trip_invitations')
    op.drop_table('trip_invitations')
    # ### end Alembic commands ###
