import { useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, Loader2, Plus, Sparkles, Trash2, Users } from 'lucide-react';
import TravelShell from '../components/TravelShell';
import TravelMap from '../components/TravelMap';
import { DESTINATIONS, MOCK_USERS } from '../data/travelData';
import { aiService } from '../services/aiService';

const steps = ['Travel type', 'Destination', 'Trip details', 'Preferences', 'AI plans'];
const defaultForm = { type: 'Solo', destination: DESTINATIONS[0], startDate: '2026-08-20', endDate: '2026-08-23', budget: '20000', style: 'Balanced', accommodation: 'Comfortable hotel', transportation: 'Private transfer', interests: ['beach', 'food'], members: ['u1'] };

export default function EnhancedCreateTripPage({ onNavigate, onCreateTrip, theme, onToggleTheme }) {
  const [step, setStep] = useState(0);
  const [form, setForm] = useState(defaultForm);
  const [plans, setPlans] = useState(null);
  const [selectedPlan, setSelectedPlan] = useState('balanced');
  const [loading, setLoading] = useState(false);
  const [query, setQuery] = useState('');
  const [memberToAdd, setMemberToAdd] = useState('u3');
  const visibleDestinations = useMemo(() => DESTINATIONS.filter((item) => `${item.name} ${item.country}`.toLowerCase().includes(query.toLowerCase())), [query]);

  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const toggleInterest = (interest) => setForm((current) => ({ ...current, interests: current.interests.includes(interest) ? current.interests.filter((item) => item !== interest) : [...current.interests, interest] }));
  const toggleType = (type) => setForm((current) => ({ ...current, type, members: type === 'Solo' ? ['u1'] : current.members.length > 1 ? current.members : ['u1', 'u2', 'u3', 'u4'] }));
  const addMember = () => { if (memberToAdd && !form.members.includes(memberToAdd)) update('members', [...form.members, memberToAdd]); };
  const removeMember = (id) => { if (id !== 'u1') update('members', form.members.filter((item) => item !== id)); };
  const generate = async () => { setLoading(true); const response = await aiService.generateTripPlan(form); setPlans(response.plans); setLoading(false); setStep(4); };
  const submit = () => {
    const plan = plans.find((item) => item.id === selectedPlan) || plans[0];
    onCreateTrip({ title: `${form.destination.name} trip`, description: `${form.style} travel plan for ${form.destination.name}.`, start_date: form.startDate, end_date: form.endDate, travel_type: form.type === 'Group' ? 'group' : 'solo', visibility: form.type === 'Group' ? 'public' : 'private', traveler_count: form.members.length, budget: Number(plan.total), status: 'planning' });
  };
  const canContinue = step === 0 || step === 1 ? true : step === 2 ? Boolean(form.startDate && form.endDate && form.budget) : true;
  const next = () => { if (step === 0 || step === 1 || step === 2) setStep(step + 1); else if (step === 3) generate(); };

  return <TravelShell onNavigate={onNavigate} theme={theme} onToggleTheme={onToggleTheme} active="My Trips" title="Create a trip">
    <div className="travel-section-heading" style={{ marginTop: 0 }}><div><span className="travel-kicker">New travel workspace</span><h2>Build a trip that feels like yours.</h2><p>Choose the basics first. The mock AI planner will compare the rest around your people, place and budget.</p></div></div>
    <div className="travel-stepper">{steps.map((item, index) => <div key={item} className="travel-step-wrap" style={{ display: 'flex', alignItems: 'center' }}><div className={`travel-step ${step >= index ? 'active' : ''}`}><span>{step > index ? '✓' : index + 1}</span>{item}</div>{index < steps.length - 1 && <div className="travel-step-line" />}</div>)}</div>

    <div className="travel-panel travel-panel-pad">
      {step === 0 && <div><span className="travel-card-kicker">01 · How are you traveling?</span><h2 style={{ font: '500 26px var(--font-serif)', margin: '9px 0 6px' }}>Set the shape of the trip.</h2><p style={{ color: 'var(--travel-muted)', fontSize: 12 }}>Solo planning stays personal. Group planning brings shared budget, members and conversation into the same space.</p><div className="travel-choice-grid" style={{ marginTop: 22 }}><button className={`travel-choice ${form.type === 'Solo' ? 'active' : ''}`} onClick={() => toggleType('Solo')}><span className="travel-choice-icon">👤</span><strong>Solo</strong><small>Plan a trip for me with a focused itinerary and Trip Assistant.</small></button><button className={`travel-choice ${form.type === 'Group' ? 'active' : ''}`} onClick={() => toggleType('Group')}><span className="travel-choice-icon">👥</span><strong>Group</strong><small>Plan with others, share decisions, chat and keep one budget together.</small></button></div></div>}
      {step === 1 && <div><span className="travel-card-kicker">02 · Where are you going?</span><h2 style={{ font: '500 26px var(--font-serif)', margin: '9px 0 6px' }}>Search or select a place on the map.</h2><p style={{ color: 'var(--travel-muted)', fontSize: 12 }}>The map is a mock location layer today and is ready to be replaced by Google Places through the backend later.</p><div className="travel-location-grid" style={{ marginTop: 18 }}><div><div className="travel-field"><label htmlFor="destination-search">Search destination</label><input id="destination-search" className="travel-input" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Try Cox's Bazar, Sajek..." /></div><div style={{ marginTop: 12 }}>{visibleDestinations.map((location) => <button key={location.id} className={`travel-location-card ${form.destination.id === location.id ? 'active' : ''}`} onClick={() => update('destination', location)}><img src={location.image} alt="" /><span><strong>{location.name}</strong><small>{location.country} · ৳{location.estimatedBudget.toLocaleString()} · {location.recommendedDays} days</small></span></button>)}</div></div><TravelMap location={form.destination} selectable onSelectLocation={(location) => { if (location.country) update('destination', location); }} height="430px" /></div></div>}
      {step === 2 && <div><span className="travel-card-kicker">03 · Dates, people and budget</span><h2 style={{ font: '500 26px var(--font-serif)', margin: '9px 0 6px' }}>Give the plan its guardrails.</h2><div className="travel-form-grid" style={{ marginTop: 20 }}><div className="travel-field"><label htmlFor="start-date">Start date</label><input id="start-date" type="date" className="travel-input" value={form.startDate} onChange={(e) => update('startDate', e.target.value)} /></div><div className="travel-field"><label htmlFor="end-date">End date</label><input id="end-date" type="date" className="travel-input" value={form.endDate} onChange={(e) => update('endDate', e.target.value)} /></div><div className="travel-field"><label htmlFor="budget">Shared budget (৳)</label><input id="budget" type="number" min="0" className="travel-input" value={form.budget} onChange={(e) => update('budget', e.target.value)} /><small>Mock planner uses this as the full trip ceiling.</small></div><div className="travel-field"><label>Travelers</label><div style={{ display: 'flex', alignItems: 'center', gap: 9, paddingTop: 8 }}><Users size={16} color="#2d6a4f" /><strong>{form.members.length} {form.type === 'Group' ? 'group members' : 'traveler'}</strong></div></div></div>{form.type === 'Group' && <div style={{ marginTop: 24, borderTop: '1px solid var(--travel-border)', paddingTop: 18 }}><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}><div><span className="travel-card-kicker">Group members</span><p style={{ color: 'var(--travel-muted)', fontSize: 11, margin: '5px 0 0' }}>Shared itinerary and group chat will be ready in the workspace.</p></div><div style={{ display: 'flex', gap: 6 }}><select className="travel-select" value={memberToAdd} onChange={(e) => setMemberToAdd(e.target.value)} style={{ width: 150 }}>{MOCK_USERS.filter((user) => user.id !== 'u1' && !form.members.includes(user.id)).map((user) => <option key={user.id} value={user.id}>{user.name}</option>)}</select><button className="travel-button" type="button" onClick={addMember}><Plus size={14} /> Add</button></div></div><div style={{ marginTop: 12 }}>{form.members.map((id) => { const member = MOCK_USERS.find((user) => user.id === id); return <div className="travel-member-row" key={id}><span className={`avatar avatar-${member.color}`}>{member.initials}</span><span><strong>{member.name}</strong><small>{id === 'u1' ? 'Admin · Current user' : 'Member · Mock invite'}</small></span>{id !== 'u1' && <button className="travel-remove" onClick={() => removeMember(id)}><Trash2 size={14} /></button>}</div>; })}</div></div>}</div>}
      {step === 3 && <div><span className="travel-card-kicker">04 · Preferences</span><h2 style={{ font: '500 26px var(--font-serif)', margin: '9px 0 6px' }}>What should the trip feel like?</h2><div className="travel-form-grid" style={{ marginTop: 20 }}><div className="travel-field"><label htmlFor="style">Travel style</label><select id="style" className="travel-select" value={form.style} onChange={(e) => update('style', e.target.value)}><option>Budget</option><option>Balanced</option><option>Luxury</option><option>Adventure</option><option>Relaxed</option><option>Family</option><option>Romantic</option><option>Photography</option><option>Food</option></select></div><div className="travel-field"><label htmlFor="accommodation">Accommodation</label><select id="accommodation" className="travel-select" value={form.accommodation} onChange={(e) => update('accommodation', e.target.value)}><option>Comfortable hotel</option><option>Local guesthouse</option><option>Eco stay</option><option>Premium resort</option></select></div><div className="travel-field"><label htmlFor="transportation">Transportation</label><select id="transportation" className="travel-select" value={form.transportation} onChange={(e) => update('transportation', e.target.value)}><option>Private transfer</option><option>Shared transport</option><option>Public transit</option><option>Flexible mix</option></select></div><div className="travel-field"><label>Interests</label><div style={{ display: 'flex', flexWrap: 'wrap', gap: 7, paddingTop: 4 }}>{['nature', 'beach', 'food', 'culture', 'history', 'adventure', 'shopping', 'photography', 'nightlife'].map((interest) => <button key={interest} type="button" onClick={() => toggleInterest(interest)} className={`travel-pill ${form.interests.includes(interest) ? 'green' : ''}`}>{form.interests.includes(interest) ? '✓ ' : ''}{interest}</button>)}</div></div></div><div className="travel-alert" style={{ marginTop: 22 }}><Sparkles size={16} color="#b86e20" /><span>The planner will compare hotel comfort, travel time, local food and weather fit around these choices.</span></div></div>}
      {step === 4 && <div><span className="travel-card-kicker">05 · Compare AI plans</span><h2 style={{ font: '500 26px var(--font-serif)', margin: '9px 0 6px' }}>Pick the rhythm that feels right.</h2><p style={{ color: 'var(--travel-muted)', fontSize: 12 }}>These are realistic mock responses from the frontend service layer. The future FastAPI endpoint can return the same shape.</p>{plans && <div className="travel-plan-scroll" style={{ marginTop: 20 }}>{plans.map((plan) => <button key={plan.id} className={`travel-panel travel-plan-card ${selectedPlan === plan.id ? 'recommended' : ''}`} onClick={() => setSelectedPlan(plan.id)} style={{ textAlign: 'left', color: 'var(--travel-text)', cursor: 'pointer' }}>{plan.recommended && <span className="travel-recommended">✦ AI recommended</span>}<span className="travel-plan-score">{plan.match}% AI match</span><h3>{plan.name}</h3><small style={{ color: 'var(--travel-muted)', fontSize: 10 }}>{plan.hotel} · {plan.comfort}</small><div className="travel-plan-price">৳{plan.total.toLocaleString()}</div><ul className="travel-plan-list"><li>{plan.activities} planned activities</li><li>{plan.transport}</li><li>{plan.food}</li></ul><div style={{ borderTop: '1px solid var(--travel-border)', paddingTop: 10, marginBottom: 13 }}><small style={{ display: 'block', color: '#2d6a4f', fontSize: 10 }}>Pros: {plan.pros.join(' · ')}</small><small style={{ display: 'block', color: 'var(--travel-muted)', fontSize: 10, marginTop: 5 }}>Trade-off: {plan.cons.join(' · ')}</small></div><span className={`travel-pill ${selectedPlan === plan.id ? 'green' : ''}`}>{selectedPlan === plan.id ? '✓ Selected' : 'Select plan'}</span></button>)}</div>}</div>}
      <div className="travel-form-actions"><button className="travel-button travel-button-ghost" onClick={() => step === 0 ? onNavigate('dashboard') : setStep(step - 1)}><ArrowLeft size={14} /> {step === 0 ? 'Cancel' : 'Back'}</button>{step < 4 ? <button className="travel-button" onClick={next} disabled={!canContinue || loading}>{loading ? <><Loader2 size={14} className="animate-spin" /> Preparing…</> : <>{step === 3 ? <><Sparkles size={14} /> Generate mock plans</> : <>Continue <ArrowRight size={14} /></>}</>}</button> : <button className="travel-button" onClick={submit}><Check size={14} /> Create {form.type.toLowerCase()} trip</button>}</div>
    </div>
  </TravelShell>;
}
